test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>
  # 一定時間経過後URLが変更し、再生不可になる問題の対策により追加。永続的なURLに変更する（23/4/10 参考1：https://blog.ingage.jp/entry/2021/01/27/090000  参考2：https://edgeguides.rubyonrails.org/active_storage_overview.html#public-access）
  public: true

# Use rails credentials:edit to set the AWS secrets (as aws:access_key_id|secret_access_key)
# TODO: パブリックアクセスが必要か確認（https://railsguides.jp/active_storage_overview.html#%E3%83%91%E3%83%96%E3%83%AA%E3%83%83%E3%82%AF%E3%82%A2%E3%82%AF%E3%82%BB%E3%82%B9）
amazon:
  service: S3
  access_key_id: <%= ENV['ACCESS_KEY_ID'] %>
  secret_access_key: <%=  ENV['SECRET_ACCESS_KEY'] %>
  region: ap-northeast-1
  bucket: fla-app-221223

  # FIXME: ローカルでS3を使用する/本番で使用する場合に変更必要 23/12/29
  # access_key_id: <%= Rails.application.credentials.dig(:aws, :access_key_id) %>
  # secret_access_key: <%= Rails.application.credentials.dig(:aws, :secret_access_key) %>

# Remember not to checkin your GCS keyfile to a repository
# google:
#   service: GCS
#   project: your_project
#   credentials: <%= Rails.root.join("path/to/gcs.keyfile") %>
#   bucket: your_own_bucket

# Use rails credentials:edit to set the Azure Storage secret (as azure_storage:storage_access_key)
# microsoft:
#   service: AzureStorage
#   storage_account_name: your_account_name
#   storage_access_key: <%= Rails.application.credentials.dig(:azure_storage, :storage_access_key) %>
#   container: your_container_name

# mirror:
#   service: Mirror
#   primary: local
#   mirrors: [ amazon, google, microsoft ]
